config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/index'
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # create a fitness controller
  resources :fitness
  resources :comments
  resources :nutritions 
  resources :profiles

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  include Visible
  belongs_to :user
  attribute  :status, :integer
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def index
    @profile = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def profile_params
    params.require(:profile).permit(:height, :weight, :sex, :activity_level, :status)
  end
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, local: true) do |form| %>
    
  <div>
    <%= form.label :user_input, "edit your Height:" %>
    <br>
    <%= form.text_area :user_input, placeholder: "I am this feet tall" %>
  </div>
  <div>
    <%= form.label :user_input, "edit your Weight:" %>
    <br>
    <%= form.text_area :user_input, placeholder: "I weigh " %>
  </div>
  <div>
    <%= form.label :user_input, "edit activity level:" %>
    <br>
    <%= form.text_area :user_input, placeholder: "I am this active " %>
  </div>
  <%= form.submit "update profile" %>
<% end %>

app/views/profiles/edit.html.erb
<header>
<%= stylesheet_link_tag 'profile' %>
</header>

<h1> Edit Profile</h1>

<%= render "form", profile: @profile %>

app/views/profiles/index.html.erb
<header>
  <%= stylesheet_link_tag 'profile' %>
</header>

<div>
  <h1>My Profile</h1>

  <p><strong>Height:</strong> <%=  %></p>
  <p><strong>Weight:</strong> <%=  %></p>
  <p><strong>Sex:</strong> <%=  %></p>
  <p><strong>Activity Level:</strong> <%=  %></p>

  <ul>
    <li><%= link_to "Edit", edit_profile_path(@profile) %></li>
    <li><%= link_to "Destroy", profile_path(@profile), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %></li>
  </ul>

  <%= link_to "Edit my Profile", new_profile_path %>
</div>

app/views/profiles/new.html.erb
<h1>Edit Profile</h1>
<header>
<%= stylesheet_link_tag 'profile' %>
</header>

<%= render "form", profile: @profile %>

app/views/profiles/show.html.erb
<header>
<%= stylesheet_link_tag 'profile' %>
</header>



<p><%= @profile.Height %></p>
<p><%= @profile.Weight %></p>
<p><%= @profile.sex %></p>
<p><%= @profile.activity_level %></p>

<ul>
  <li><%= link_to "Edit", edit_profile_path(@profile) %></li>
  <li><%= link_to "Destroy", profile_path(@profile), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>