config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/index'
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # create a fitness controller
  resources :fitness
  resources :comments
  resources :nutritions 
  resources :profiles

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/nutrition.rb
# frozen_string_literal: true

class Nutrition < ApplicationRecord
  belongs_to :user
  attribute  :status, :integer
  validates :food_name, presence: true
  validates :serving_units, presence: true
  validates :serving_weight_grams, presence: true
  validates :calories, presence: true
  validates :protein, presence: true
  validates :total_fat, presence: true
  validates :total_carbohydrates, presence: true
  validates :sugar, presence: true
end

app/controllers/nutritions_controller.rb
class NutritionsController < ApplicationController

  def index
    @nutrition = Nutrition.all
  end

  def show
    @nutrition = Nutrition.find(params[:id])
  end

  def new
    @nutrition = Nutrition.new
  end

  def create
    response = make_api_request(params[:nutrition][:user_input])
    fitness_data = extract_data_from_api_response(response)

    fitness_data.each do |data|
      @nutrition = current_user.nutritions.build(
        serving_units: data['serving_unit'],
        serving_weight_grams: data['serving_weight_grams'],
        food_name: data['food_name'],
        calories: data['nf_calories'],
        protein: data['nf_protein'],
        total_fat: data['nf_total_fat'],
        total_carbohydrates: data['nf_total_carbohydrate'],
        sugar: data['nf_sugars']
        # Add other attributes as needed
      )

      # Save each nutrition entry inside the loop
      unless @nutrition.save
        puts "Error saving nutrition entry: #{@nutrition.errors.full_messages.join(', ')}"
        render :new and return
      end
    end

    puts "All nutrition entries saved successfully!"
    redirect_to nutritions_path, notice: 'Nutritions entries logged successfully.'
  end

  def edit
    @nutrition = Nutrition.find(params[:id])
  end

  def update
    @nutrition = Nutrition.find(params[:id])

    if @nutrition.update(nutrition_params)
      redirect_to @nutrition
    else
      render :edit, :unprocessable_entity
    end
  end 

  def destroy
    @nutrition = Nutrition.find(params[:id])
    @nutrition.destroy

    redirect_to root_path, status: :see_other
  end

  private
    
    def make_api_request(input)
      url = 'https://trackapi.nutritionix.com/v2/natural/nutrients'
      headers = {
        'Content-Type': 'application/json',
        'x-app-id': '3b10b065',
        'x-app-key': '2c3c4bf48541fceb8358b9637625bf12'
      }
      payload = {
        query: input
      }
      response = RestClient.post(url, payload.to_json, headers)
      JSON.parse(response.body)
    end
  
    def extract_data_from_api_response(response)
      response['foods']
    end
  
    def nutrition_params
      params.require(:nutrition).permit(:food_name, :serving_units, :serving_weight_grams, :protein, :calories, :total_carbohydrates, :total_fat, :sugar)
    end

  end 

app/helpers/nutritions_helper.rb
# frozen_string_literal: true

module NutritionsHelper
end

app/views/nutritions/_form.html.erb
<h1>New Meal</h1>
<%= form_with(model: @nutrition, url: nutritions_path, method: :post) do |form| %>
    <div class="field">
    <%= form.label :For %>
    <%= form.hidden_field :log_date, value: Date.current %>
    <span><%= Date.current %></span>
  </div>
  <div>
    <%= form.label :user_input, "Enter your Meal:" %>
    <br>
    <%= form.text_area :user_input, placeholder: "I ate tuna sandwich with celery" %>
  </div>
  <%= form.submit "Log meal" %>
<% end %>
  

app/views/nutritions/edit.html.erb
<header>
<%= stylesheet_link_tag 'nutrition' %>
</header>

<h1> Edit Meals</h1>

<%= render "form", nutrition: @nutrition %>

app/views/nutritions/index.html.erb
<h1>Nutrition</h1>
<header>
<%= stylesheet_link_tag 'nutrition' %>
</header>

<table>
  <thead>
    <tr>
      <th>Food Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @nutrition.each do |nutrition| %>
      <tr>
        <td><%= nutrition.food_name %></td>
        <td><%= link_to 'Details', nutrition_path(nutrition) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Meal", new_nutrition_path %>

app/views/nutritions/new.html.erb
<header>
<%= stylesheet_link_tag 'nutrition' %>
</header>

<%= render "form", nutrition: @nutrition %>

app/views/nutritions/show.html.erb
<header>
<%= stylesheet_link_tag 'nutrition' %>
</header>

<table>
  <tr>
    <th colspan="2"><h1><%= @nutrition.food_name %></h1></th>
  </tr>

  <tr>
    <th>Serving Weight per Grams</th>
    <th>Serving Units</th>
    <th>Calories</th>
    <th>Protein</th>
    <th>Total Fat</th>
    <th>Total Carbs</th>
    <th>Sugar</th>
  </tr>
  <tr>
    <td><%= @nutrition.serving_units %></td>
    <td><%= @nutrition.serving_weight_grams %></td>
    <td><%= @nutrition.calories %></td>
    <td><%= @nutrition.protein %></td>
    <td><%= @nutrition.total_fat %></td>
    <td><%= @nutrition.total_carbohydrates %></td>
    <td><%= @nutrition.sugar %></td>
  </tr>
</table>

 
<ul>
  <li><%= link_to "Edit", nutrition_path(@nutrition) %></li>
  <li><%= link_to "Destroy", nutrition_path(@nutrition), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>