config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile/index'
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  # create a fitness controller
  resources :fitness
  resources :comments
  resources :nutritions 
  resources :profiles

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_header.html.erb
<div style="position: fixed; top: 0; left: 0; width: 100%; display: flex; justify-content: space-between; align-items: center; background-color: black; padding: 10px; z-index: 100;">
  <%= link_to 'Home', root_path, class: "btn btn-light"%> 
  <% if user_signed_in? %>
    <%= link_to "Fitness", new_fitness_path, class: "btn btn-light"%> 
  <% end %>
  <% unless user_signed_in? %>
    <%= link_to "Sign up!", new_user_registration_path, class: "btn btn-light"%>
  <% else %>
    <%= link_to 'Nutrition', nutritions_path, class:"btn btn-light" %>
    <%= link_to 'Profile', profiles_path, class:"btn btn-light" %>
  <% end %>
  <div style="text-align: right; color: white;">
    <% if user_signed_in? %>
      <div style="display: flex; align-items: center;">
        <div style="margin-right: 10px;"> <%= current_user.username %>!</div>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-light" %>
      </div>
    <% else %>
      <%= button_to "Sign in", new_user_session_path, class: "btn btn-light" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome To Feast N Fit</h1>
<%= stylesheet_link_tag 'home' %>